### ISSUE TITLE
Web_1 container

### ISSUE THREAD

**Issue by ChRock8** [phansiri/check_in_check_out_bks#7]
I can get all the way to the last step then get this error 

> ERROR: No container found for web_1

when I try to run this in the in CMD:

`docker-compose exec web python manage.py migrate`

When I check the containers in Docker, the db container is good but the web_1 container gives me this error:

> web_1 | standard_init_linux.go:219: exec user process caused: no such file or directory
check_in_check_out_bks_web_1 exited with code 1

I verified the .env and .end.db have matching info and followed all your steps exactly, even starting over and still get the same error.

**Comment by phansiri** [comment]
I do apologize if the instructions were not clear. I have attached screenshots from a fresh installation of the image to running the web application. The instructions are performed on a Mac Book Pro.


## Step 1
In order to simulate a fresh install, I made sure that I have no docker containers running: `docker-compose down -v`. The `-v` ensures I remove any volumes I had attached to it. Afterwards I deleted all of the stored images. It could be done through the GUI or running `docker image prune -a`. From there, I rebuilt the image and ran it with the command:`docker-compose up --build`.
<img width="1920" alt="Screen Shot 2021-01-18 at 6 39 07 PM" src="https://user-images.githubusercontent.com/8903238/104899379-1ec7c900-59be-11eb-8df0-897f85ea9d38.png">

## Step 2 - Verify
Once docker-compose finishes, the screen should look like the image below.
<img width="1920" alt="Screen Shot 2021-01-18 at 6 46 23 PM" src="https://user-images.githubusercontent.com/8903238/104899901-c0e7b100-59be-11eb-91f3-1e1d5276b975.png">

## Step 3
`Control + C` to stop the docker container and then run `docker-compose down` to shut it down.
<img width="1920" alt="Screen Shot 2021-01-18 at 6 47 37 PM" src="https://user-images.githubusercontent.com/8903238/104900139-0efcb480-59bf-11eb-8957-e1659d8103cd.png">

## Step 4
Once it is shut down, bring it back up with `docker-compose up` (in the screenshot, I added the `--build` because it is a habit of mine to ensure anything I edited in the docker files are up to date in the containers)
<img width="1920" alt="Screen Shot 2021-01-18 at 6 47 49 PM" src="https://user-images.githubusercontent.com/8903238/104900436-68fd7a00-59bf-11eb-8067-76af4ab62a43.png">

## Step 5
Everything that was needed to migrate into the database ought to have done it automatically because of the `entrypoint.sh` file which runs in the Dockerfile.
<img width="1920" alt="Screen Shot 2021-01-18 at 6 48 05 PM" src="https://user-images.githubusercontent.com/8903238/104900495-74e93c00-59bf-11eb-9c76-6a5f02288566.png">

## Step 5.1 - Verify
The command `docker-compose ps` lists all running containers. You ought to see the two containers.
<img width="1920" alt="Screen Shot 2021-01-18 at 7 02 11 PM" src="https://user-images.githubusercontent.com/8903238/104900672-b0840600-59bf-11eb-859b-902fa8dbd19f.png">


This ought to help. However, the just quickly answer your question.
> You cannot run `exec` commands on docker-compose unless the container is running through the `docker-compose up` command first.

I hope it all goes well.

**Comment by ChRock8** [comment]
My issues is actually with getting the web_1 docker container up and running. I can clone the code via Git and create the .env and .env.db files just fine. When I run `docker-compose up --build` I get this error (three screen shots to show you my entire terminal and a fourth to show you what the log in Docker says)
![docker-1](https://user-images.githubusercontent.com/12198111/104959363-688fce00-5a15-11eb-892e-610f7b620e86.PNG)
![docker-2](https://user-images.githubusercontent.com/12198111/104959368-69c0fb00-5a15-11eb-84a3-2cd222e87670.PNG)
![docker-3](https://user-images.githubusercontent.com/12198111/104959369-6a599180-5a15-11eb-8330-d2fbfaaaf8b7.PNG)
![docker-4](https://user-images.githubusercontent.com/12198111/104959476-9bd25d00-5a15-11eb-8860-27b12d52fe89.PNG)

The db container is running just fine.

I actually fixed this by importing the entrypoint.sh file into Notepad++ and changing the encoding from CD LF to LF and that did the trick - both containers are now up and running for me fine. Credit goes to this stackoverflow post:

https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory
